"""initial

Revision ID: 194a6b8b4198
Revises: 
Create Date: 2022-06-17 17:25:16.286116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194a6b8b4198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_srorage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('graph1', sa.Float(), nullable=True),
    sa.Column('graph2', sa.Float(), nullable=True),
    sa.Column('graph3', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('file_srorage')
    # ### end Alembic commands ###
